# Generated by Django 2.2 on 2019-04-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('star', models.IntegerField()),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('cert_start', models.TimeField()),
                ('cert_end', models.TimeField()),
            ],
        ),
    ]
