# Generated by Django 2.2 on 2019-04-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190425_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='cert_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='cert_start',
            field=models.DateTimeField(null=True),
        ),
    ]
